# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoShowMd < Formula
  desc "Lightweight macOS markdown file viewer and navigator"
  homepage "https://github.com/lfx/go-show-md"
  version "1.0.5"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/lfx/go-show-md/releases/download/v1.0.5/go-show-md_Darwin_x86_64.tar.gz"
    sha256 "d48dee310a582fa7795787ce8eed5bffebfc317f8d183f29fa9009c4aa32fef4"

    define_method(:install) do
      bin.install "go-show-md"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/lfx/go-show-md/releases/download/v1.0.5/go-show-md_Darwin_arm64.tar.gz"
    sha256 "ff6f6f4e92162bd2bd50b779f15cb280bddd0d67e21fb39f71083e3a0dcdfd11"

    define_method(:install) do
      bin.install "go-show-md"
    end
  end

  test do
    assert_path_exists bin/"go-show-md"
    assert_predicate bin/"go-show-md", :executable?
  end
end
