# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MacPortBar < Formula
  desc "A lightweight macOS menu bar utility written in Go that automatically scans for and lists locally running HTTP services."
  homepage "https://github.com/lfx/mac-port-bar"
  version "1.0.3"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/lfx/mac-port-bar/releases/download/v1.0.3/mac-port-bar_Darwin_x86_64.tar.gz"
    sha256 "42edf5faffd4f8b4c3582e7895b994c9b0a4cd2c3edabbe622327fe2d6613ef2"

    define_method(:install) do
      bin.install "mac-port-bar"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/lfx/mac-port-bar/releases/download/v1.0.3/mac-port-bar_Darwin_arm64.tar.gz"
    sha256 "d22b16cb438cef173d7d4656de6f4c579b8979312cb2c9a482872a2949d43da4"

    define_method(:install) do
      bin.install "mac-port-bar"
    end
  end

  test do
    assert_path_exists bin/"mac-port-bar"
    assert_predicate bin/"mac-port-bar", :executable?
  end
end
