# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MacPortBar < Formula
  desc "Lightweight macOS menu bar utility listing locally running HTTP services"
  homepage "https://github.com/lfx/mac-port-bar"
  version "1.0.4"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/lfx/mac-port-bar/releases/download/v1.0.4/mac-port-bar_Darwin_x86_64.tar.gz"
    sha256 "31d732db0441b97774a0907539ec79a52454f707864947482a703bd5facf2f3f"

    define_method(:install) do
      bin.install "mac-port-bar"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/lfx/mac-port-bar/releases/download/v1.0.4/mac-port-bar_Darwin_arm64.tar.gz"
    sha256 "1659bf9cff31b68c31af09071f864fa8e88f24a8b31748d8c43ee69dfeb597af"

    define_method(:install) do
      bin.install "mac-port-bar"
    end
  end

  service do
    run opt_bin/"mac-port-bar"
    keep_alive successful_exit: false
    log_path var/"log/mac-port-bar.log"
    error_log_path var/"log/mac-port-bar.log"
  end

  test do
    assert_path_exists bin/"mac-port-bar"
    assert_predicate bin/"mac-port-bar", :executable?
  end
end
